# Generated by ChatGPT - proof of concept ingestion file
import requests
import psycopg2
from psycopg2.extras import execute_values
from datetime import datetime
import locale
import time
import os
from dotenv import load_dotenv

# -----------------------------
# Database configuration
# -----------------------------
load_dotenv()

DB_CONFIG = {
    "dbname": os.getenv("DB_NAME"),
    "user": os.getenv("DB_USER"),
    "password": os.getenv("DB_PASSWORD"),
    "host": os.getenv("DB_HOST"),
    "port": int(os.getenv("DB_PORT", 5432)),
}


# -----------------------------
# Helper to parse release dates
# -----------------------------
def parse_release_date(date_str):
    if not date_str:
        return None
    # Try common English format first
    try:
        return datetime.strptime(date_str, "%d %b, %Y")
    except ValueError:
        pass
    # Try localized format (Russian / Steam store localized dates)
    try:
        locale.setlocale(locale.LC_TIME, "ru_RU.UTF-8")  # for "дек." etc.
        return datetime.strptime(date_str, "%d %b. %Y г.")
    except Exception:
        return None
    finally:
        locale.setlocale(locale.LC_TIME, "")  # reset to system default


# -----------------------------
# Fetch game details
# -----------------------------
def fetch_game_details(appid):
    url = f"https://store.steampowered.com/api/appdetails?appids={appid}"
    resp = requests.get(url)
    data = resp.json()
    if not data[str(appid)]["success"]:
        return None
    game = data[str(appid)]["data"]
    release_date_str = game.get("release_date", {}).get("date")
    release_date = parse_release_date(release_date_str)

    return {
        "appid": appid,
        "name": game.get("name"),
        "developers": ",".join(game.get("developers", [])) or None,
        "publishers": ",".join(game.get("publishers", [])) or None,
        "platforms": ",".join([k for k, v in game.get("platforms", {}).items() if v])
        or None,
        "release_date": release_date,
        "capsule_imageV5": game.get("header_image"),
    }


# -----------------------------
# Example list of appids
# -----------------------------
GAME_APPIDS = [
    413150,
    578080,
    105600,
    620,
    570,  # replace with your 50 appids
]


# -----------------------------
# Main ingestion logic
# -----------------------------
def main():
    conn = psycopg2.connect(**DB_CONFIG)
    cur = conn.cursor()

    games_to_insert = []

    for appid in GAME_APPIDS:
        print(f"Fetching game {appid}...")
        game_data = fetch_game_details(appid)
        if not game_data:
            print(f"Failed to fetch game {appid}")
            continue
        games_to_insert.append(
            (
                game_data["appid"],
                game_data["name"],
                game_data["capsule_imageV5"],
                game_data["developers"],
                game_data["publishers"],
                game_data["platforms"],
                game_data["release_date"],
                datetime.utcnow(),  # last_updated
            )
        )
        time.sleep(0.2)  # be polite to Steam's API

    # Insert into database using upsert (on conflict update)
    insert_sql = """
    INSERT INTO games (appid, name, capsule_imageV5, developers, publishers, platforms, release_date, last_updated)
    VALUES %s
    ON CONFLICT (appid) DO UPDATE
    SET
        name = EXCLUDED.name,
        capsule_imageV5 = EXCLUDED.capsule_imageV5,
        developers = EXCLUDED.developers,
        publishers = EXCLUDED.publishers,
        platforms = EXCLUDED.platforms,
        release_date = EXCLUDED.release_date,
        last_updated = EXCLUDED.last_updated
    """
    execute_values(cur, insert_sql, games_to_insert)
    conn.commit()
    cur.close()
    conn.close()
    print("Done!")


if __name__ == "__main__":
    main()
